###Get All Employee
GET http://localhost:3000/employee


###Post an employee
POST http://localhost:3000/employees
Content-Type: application/json
//LOVEEE
{
    "name": "Deither",
    "age": 21
}


###Patch one employee
PATCH http://localhost:3000/employee/id



###Get all users
GET http://localhost:3000/user